name: Package GoogleCast SDK

on:
  schedule:
    - cron: '0 */24 * * *'  # Run every 24 hours
  workflow_dispatch:  # Allow manual triggers

permissions:
  contents: write  # Needed for creating releases and pushing changes
  
jobs:
  check-and-package:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Check for new SDK version
        id: check
        run: |
          ./.scripts/check-version.sh
        
      - name: Download and package SDK
        if: steps.check.outputs.has_new_version == 'true'
        run: |
          ./.scripts/download-sdk.sh
          
      - name: Calculate Checksum
        if: steps.check.outputs.has_new_version == 'true'
        id: checksum
        run: |
          echo "sha256=$(swift package compute-checksum GoogleCast.xcframework.zip)" >> $GITHUB_OUTPUT

      - name: Update Package.swift
        if: steps.check.outputs.has_new_version == 'true'
        run: |
          VERSION=${{ steps.check.outputs.version }}
          CHECKSUM=${{ steps.checksum.outputs.sha256 }}
          sed -i '' "s|/VERSION/|/$VERSION/|g" Package.swift
          sed -i '' "s|CHECKSUM|$CHECKSUM|g" Package.swift
          
      - name: Commit and Push Changes
        if: steps.check.outputs.has_new_version == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Package.swift latest_version.txt
          git commit -m "chore: Update to GoogleCast SDK version ${{ steps.check.outputs.version }}"
          git push
          
      - name: Create Release
        if: steps.check.outputs.has_new_version == 'true'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            GoogleCast.xcframework.zip
          tag_name: ${{ steps.check.outputs.version }}
          generate_release_notes: true
          body: |
            GoogleCast SDK version ${{ steps.check.outputs.version }}
            
            ## Installation
            ```swift
            dependencies: [
                .package(url: "https://github.com/dushantSW/googlecast-ios-sdk-xcframeworks.git", .exact("${{ steps.check.outputs.version }}"))
            ]
            ```
